import 'package:flutter/material.dart';
import 'dart:math';
List<String> Kelimeing = [
  "Fact",
  "Craftsman",
  "Landmark",
  "Heaven",
  "Monument",
  "West",
  "Destination",
  "East",
  "Bucket list",
  "The Pool of Abraham",
  "Unique",
  "Fictional",
  "Last",
  "Civilization",
  "Entire",
  "Settlement",
  "Head to",
  "Distant",
  "Climate",
  "Cradle of cilizations",
  "Tradition",
  "Numerous",
  "Habit",
  "Acropolis",
  "Diverse",
  "Slope",
  "Enhance",
  "Remain",
  "Heritage",
  "Mythical",
  "Preserve",
  "Layer",
  "Date back",
  "Shore",
  "Underground",
  "Mound",
  "Wonder",
  "Source",
  "Flooded",
  "Breathtaking",
  "Tomb",
].toList();
//Başka bir sayfada bu kelimeleri çekebilmek için .toList() kulllanıyoruz.
List<String> KelimeTR = [
  "Hakikat",
  "Usta",
  "Kent simgesi",
  "Cennet",
  "Anıt",
  "Batı",
  "Rota",
  "Doğu",
  "Ölmeden once yapılacaklar listesi",
  "Balıklı göl",
  "Eşsiz",
  "Hayali",
  "Sürmek",
  "Medeniyet",
  "Tüm",
  "Yerleşim",
  "Yola çıkmak",
  "Uzak",
  "İklim",
  "Medeniyetler beşiği",
  "Gelenek",
  "Sayısız",
  "Alışkanlık",
  "Kale",
  "Çeşitli",
  "Yamaç",
  "Geliştirmek",
  "Kalıntı",
  "Miras",
  "Hayali",
  "Korumak",
  "katman",
  "Daha once tarihe ait olmak",
  "Sahil",
  "Yeraltı",
  "Tümsek",
  "Harika",
  "Kaynak",
  "Taşmış",
  "Nefes kesici",
  "Türbe",
].toList();
List<String>Ressi=[
  "Reso/doga1.jpg",
  "Reso/usta.jpg",
  "Reso/kkentresmi.jpg",
  "Reso/cennet.jpg",
  "Reso/anit.jpg",
  "Reso/bati.jpg",
  "Reso/rota.jpg",
  "Reso/dogu.jpg",
  "Reso/del.jpg",
  "Reso/balikligol.jpg",
  "Reso/doga1.jpg",
  "Reso/hayali.jpg",
  "Reso/surmek.jpg",
  "Reso/medeniyet.jpg",
  "Reso/doga1.jpg",
  "Reso/yerlesim.jpg",
  "Reso/yolacık.jpg",
  "Reso/uzak.jpg",
  "Reso/iklim.jpg",
  "Reso/medeniyet.jpg",
  "Reso/gelenek.jpg",
  "Reso/doga1.jpg",
  "Reso/aliskanlik.jpg",
  "Reso/kale.jpg",
  "Reso/doga1.jpg",
  "Reso/yamac.jpg",
  "Reso/doga1.jpg",
  "Reso/kalinti.png",
  "Reso/miras.jpg",
  "Reso/hayali.jpg",
  "Reso/korumak.jpg",
  "Reso/katman.jpg",
  "Reso/doga1.jpg",
  "Reso/sahil.jpg",
  "Reso/yeralti.jpg",
  "Reso/tumsek.jpg",
  "Reso/harika.jpg",
  "Reso/kaynak.jpg",
  "Reso/tasmis.jpg",
  "Reso/nefeskesici.jpg",
  "Reso/turbe.jpg",
];
